import React from 'react'

function About() {
  return (
    <div>
      <h1 className='text-2xl font-bold'>About</h1>
  <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus quisquam aperiam commodi at exercitationem quam culpa itaque amet ipsam, debitis voluptas architecto perspiciatis dolore magni a corrupti excepturi, iste tenetur. Quas laudantium hic neque quaerat. Illum laboriosam velit qui perspiciatis, repellat porro eaque molestiae quos recusandae tempore incidunt sit! Ad excepturi unde praesentium, distinctio aliquam officiis. Delectus ducimus necessitatibus earum quae vitae modi dolores iste maxime aspernatur itaque soluta, dolorem similique error consequuntur et odio, provident, sapiente accusamus? Est optio soluta aperiam sint. Molestiae in ea molestias, error rerum praesentium debitis amet sed dignissimos nesciunt. Enim quaerat, voluptatem nesciunt voluptatibus aperiam quibusdam non eligendi iste, porro architecto veniam corporis deleniti omnis amet, ducimus temporibus? Obcaecati tenetur deleniti quo quidem minus, quia dolorem repellendus magnam praesentium, illum, velit ipsa cum tempora veniam a ipsum voluptates laborum delectus quas. Eligendi autem explicabo nemo nam quasi at laboriosam, aliquid velit voluptate illo quaerat labore expedita voluptatum voluptatibus corrupti a consectetur ea officia! Dolorem ad nam dolorum, inventore cum vel optio earum, ab delectus aperiam doloremque itaque reprehenderit placeat reiciendis eligendi. Temporibus delectus aliquam minus illo quos voluptas voluptatibus similique corporis repellat quaerat nihil porro, explicabo perspiciatis odit aperiam vero quasi harum. Laboriosam facilis corrupti a odio quaerat voluptatibus molestias ducimus iusto. Error inventore modi commodi non a qui fuga. Reprehenderit iusto quia facere error et, eaque, architecto praesentium a tenetur commodi quasi nulla ab quo. Debitis itaque distinctio quod consequuntur aut nemo, non, ad rerum quas a perferendis culpa impedit. Mollitia saepe voluptatibus eaque ratione quas quasi dolore provident unde ipsam illum sit maiores fuga, quam necessitatibus tenetur facilis officiis vel optio eum assumenda atque numquam deserunt ab at? Delectus nobis laborum nemo esse nisi error hic ipsam! Vel voluptas tempore delectus, molestiae vero harum, sint facere laborum ad soluta esse eos quisquam placeat quo ratione, dignissimos modi a eveniet reprehenderit quam! Minus at iste blanditiis explicabo mollitia perspiciatis officiis! Sunt placeat voluptate ex tenetur qui repellendus temporibus, debitis, aut quae, explicabo animi. Nulla libero est consequatur ullam natus. Aperiam, quo velit itaque amet et nulla, pariatur libero porro, rerum iste consequatur molestias.</p>
    </div>
  )
}

export default About
